# NumPy Array Tutorial
This tutorial covers essential NumPy concepts, including array creation, attributes, operations, broadcasting, storage order, and linear algebra basics.

## Introduction
NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays efficiently.

In [1]:
import numpy as np

## Creating NumPy Arrays
NumPy provides various methods to create arrays:

In [2]:
# Creating arrays using different methods
a = np.array([1, 2, 3, 4, 5])  # Using array()
b = np.zeros((3, 3))  # Using zeros()
c = np.ones((2, 4))  # Using ones()
d = np.linspace(0, 10, 5)  # Using linspace()
e = np.arange(0, 10, 2)  # Using arange()
f = np.eye(4)  # Using eye() for identity matrix
g = np.diag([1, 2, 3, 4])  # Using diag()
a, b, c, d, e, f, g

(array([1, 2, 3, 4, 5]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([ 0. ,  2.5,  5. ,  7.5, 10. ]),
 array([0, 2, 4, 6, 8]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]))

## Difference Between Lists and NumPy Arrays
NumPy arrays support element-wise operations, whereas lists behave differently.

In [3]:
# List vs NumPy array operations
list1 = [1, 2, 3, 4]
array1 = np.array([1, 2, 3, 4])

print('List addition:', list1 + list1)  # Concatenation
print('NumPy array addition:', array1 + array1)  # Element-wise addition

print('List multiplication:', list1 * 2)  # Repeats list
print('NumPy array multiplication:', array1 * 2)  # Element-wise multiplication

List addition: [1, 2, 3, 4, 1, 2, 3, 4]
NumPy array addition: [2 4 6 8]
List multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
NumPy array multiplication: [2 4 6 8]


## Important Array Methods
NumPy provides several useful functions to analyze arrays:

In [5]:
# Array functions
arr = np.array([10, 20, 5, 8])
print('Max:', arr.max())
print('Min:', arr.min())
print('Sum:', arr.sum())
print('Index of max:', arr.argmax())
print('Index of min:', arr.argmin())

Max: 20
Min: 5
Sum: 43
Index of max: 1
Index of min: 2


## Broadcasting in NumPy
Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [6]:
# Broadcasting example
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])  # Shape (3,)
C = A + B  # Broadcasting
print(C)

[[2 4 6]
 [5 7 9]]


## Row-Major and Column-Major Storage
NumPy stores arrays in row-major order by default, but you can change it to column-major using `order='F'`.

In [7]:
# Row-major vs Column-major
arr = np.array([[1, 2], [3, 4]], order='C')
print('Row-major:', arr.flatten(order='C'))
print('Column-major:', arr.flatten(order='F'))

Row-major: [1 2 3 4]
Column-major: [1 3 2 4]


## Array Attributes
Some important attributes of NumPy arrays include:

In [8]:
# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)
print('Number of dimensions:', arr.ndim)

Shape: (2, 3)
Number of dimensions: 2


## Concept of Axis in NumPy
Axis 0 refers to rows (vertical operations), while Axis 1 refers to columns (horizontal operations).

In [9]:
# Axis example
arr = np.array([[1, 2], [3, 4]])
print('Sum along axis 0:', arr.sum(axis=0))  # Column-wise sum
print('Sum along axis 1:', arr.sum(axis=1))  # Row-wise sum

Sum along axis 0: [4 6]
Sum along axis 1: [3 7]


## Reshaping Arrays
We can reshape arrays into different dimensions.

In [ ]:
# Reshaping example
arr = np.arange(6).reshape(2, 3)
print(arr)

## Splitting Arrays
NumPy provides functions to split arrays into multiple parts.

In [ ]:
# Splitting an array
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print(split_arr)

## hsplit vs vsplit
- `hsplit()` splits along columns (horizontally)
- `vsplit()` splits along rows (vertically)

In [ ]:
# hsplit vs vsplit
arr = np.arange(16).reshape(4, 4)
print('Horizontal Split:', np.hsplit(arr, 2))
print('Vertical Split:', np.vsplit(arr, 2))

## Stacking Arrays
NumPy allows stacking arrays vertically and horizontally.

In [ ]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Horizontal Stack:', np.hstack((a, b)))
print('Vertical Stack:', np.vstack((a, b)))

## Simple Linear Algebra with NumPy
NumPy provides functions for basic linear algebra operations.

In [ ]:
# Linear algebra example
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Matrix Multiplication:', np.dot(A, B))
print('Transpose of A:', A.T)